project_id = "kmeyrlplsvdjxowxmzan"

[functions.send-quote]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.send-quote-gmail]
verify_jwt = false

[functions.send-quote-sendgrid]
verify_jwt = false

[functions.compute-quote]
verify_jwt = false

[functions.get-logo-base64]
verify_jwt = false