project_id = "cwafbmbmgisusbdypcux"

[functions.assign-admin-role]
verify_jwt = false

[functions.compute-quote]
verify_jwt = false

[functions.generate-quote-pdf]
verify_jwt = false

[functions.resend-api]
verify_jwt = false

[functions.update-quote-status]
verify_jwt = false
